apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: test-chico
data:
  # DB_HOST from Terraform Output: rds_endpoint
  DB_HOST: "test-chico-db.c3geoy682q08.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "blog"
  # Application settings
  NODE_ENV: "production"
  CORS_ALLOWED_ORIGINS: "https://chico.exam.ezopscloud.tech" # Production Frontend Domain
  DB_SSL: "true"
