apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: stg-chico
data:
  # DB_HOST from Terraform Output: rds_endpoint
  # Removing :5432 port suffix as Node usually expects host only, or handle port in DB_PORT
  DB_HOST: "stg-chico-db.c1miyqamydgg.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "blog"
  # Application settings
  NODE_ENV: "production"
