apiVersion: v1
kind: Service
metadata:
  name: ezops-backend-svc
  namespace: test-chico
spec:
  selector:
    app: ezops-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
