apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: stg-chico
data:
  # Application settings
  # Application settings
  NODE_ENV: "production"
  CORS_ALLOWED_ORIGINS: "https://app-ezops.gratianovem.com.br,http://localhost:8080"
  DB_SSL: "true"
