apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ezops-backend-ingress
  namespace: stg-chico
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # SSL / HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:563702590660:certificate/543551b9-5510-4af6-bdc6-268c5d54e1be
    # Health checks
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
spec:
  rules:
    # Staging Domain: api.chico.exam.ezopscloud.tech 
    # (Matches what you will configure in Cloudflare CNAME to point to ALB)
    - host: api-ezops.gratianovem.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ezops-backend-svc
                port:
                  number: 80
